# Generated by Django 2.0.2 on 2018-10-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(verbose_name={'own': 1, 'school': 2})),
                ('photo_path', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': '照片表',
                'verbose_name_plural': '照片表',
            },
        ),
    ]
